version: '3'

services: 
    app:
        build: .
        container_name: countries
        # command: python manage.py runserver 0.0.0.0:8000
        entrypoint: ["bash","wait-for-postgres.sh"]
        # command: >
        #     sh -c "python manage.py collectstatic --noinput &&
        #             python manage.py migrate &&
        #             python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - .:/usr/src/app
        ports: 
            - "8000:8000"
        depends_on: 
            - postgis
        
    postgis:
        image: kartoza/postgis:12.0
        environment:
            - DEBUG=True            
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"