# Generated by Django 2.2.10 on 2021-07-27 17:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(default='Default', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'countries',
                'managed': True,
            },
        ),
    ]
