# Generated by Django 3.2.5 on 2021-08-01 12:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default='MULTIPOLYGON EMPTY', srid=4326),
        ),
    ]
